### PR TITLE
Move defaultOptions into GoogleChartsService

### LINKED ISSUE #39: Default options are not inherited by child components
If I override the `GoogleChartComponent` to add default options:
```javascript
import GoogleChart from 'ember-google-charts/components/google-chart';

export default GoogleChart.extend({
  defaultOptions: {
    legend: {
      position: 'none',
    },
  },
});
```

I would expect all chart types to inherit these options. However when I add a chart type component to my template:
```javascript
{{pie-chart data=model}}
```
it does not inherit the options. In the example above, I would expect the pie chart to not have a legend, but the actual result renders a legend to the right of the chart.

### PR DESCRIPTION
**Pull request by steven-ferguson**
Fixes #39

### CODE REVIEW

**Comment by steven-ferguson** [comment]
Not sure why it had trouble building on Travis. @sir-dunxalot can you try kicking the build off again?

**Comment by sir-dunxalot** [comment]
Just restarted the build so let's see what that does.

**Comment by steven-ferguson** [comment]
Looks like updating the Travis config to use node 6 fixed the build issue

**Comment by sir-dunxalot** [comment]
@steven-ferguson I had to make a couple of updates to make the test suite pass and ensure backwards compatibility but now this update is on master, to be released soon!

**Pull request merged**
