### PR TITLE
Clean up async chart loading

### PR DESCRIPTION
**Pull request by steven-ferguson**
This PR accomplishes two things:

1) Fixes errors encountered when the chart was destroyed before the google libraries are loaded. Currently, if the chart component is destroyed before the [`loadPackages` promise is resolved](https://github.com/sir-dunxalot/ember-google-charts/blob/2558a990793c2a32672b3adf71f2f14bfc759071/addon/components/google-chart.js#L115) you will get an error because the promise callback is trying to access properties on the destroyed component. [ember-concurrency's](https://github.com/machty/ember-concurrency) `task` solves this, by canceling the chart render call if the component is destroyed.

2) Cleans up the logic for ensuring the chart libraries are loaded by using `setOnLoadCallback`

### CODE REVIEW

**Comment by sir-dunxalot** [comment]
Thanks! I will review this PR this weekend.

**Comment by sir-dunxalot** [comment]
Sorry, haven't been able to review this yet but am hoping to get to it soon.

**Comment by sir-dunxalot** [comment]
Sorry for the delay. The code changes look good. I have one question:

1. Do these changes need any documentation changes? I don't believe so, because these are private method changes, but I just want to make sure we don't need to change any docs, examples, or acceptance tests.

**Comment by steven-ferguson** [comment]
Correct, this will not change any public api behavior so no documentation updates needed.

**Pull request merged**
